basePath: /v1/api
definitions:
  entities.Device:
    properties:
      id:
        type: integer
      subscribe_announcement:
        type: boolean
      subscribe_tx:
        type: boolean
      token:
        type: string
    type: object
  models.Device:
    description: ID account information
    properties:
      id:
        type: integer
      subscribe_announcement:
        type: boolean
      subscribe_tx:
        type: boolean
      timestamp:
        type: string
      token:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Geting for welcome endpoint
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Welcome
  /v1/api/device:
    post:
      consumes:
      - application/json
      description: Create new infomation of device
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Device'
            type: array
      tags:
      - device
  /v1/api/devices:
    get:
      consumes:
      - application/json
      description: Get all existing of devices
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Device'
            type: array
      tags:
      - devices
  /v1/api/devices/{id}:
    get:
      consumes:
      - application/json
      description: Get for device details
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Device'
      tags:
      - device
    put:
      consumes:
      - application/json
      description: Update device information
      parameters:
      - description: SubscribeTx
        in: body
        name: subscribe_tx
        required: true
        schema:
          type: string
      - description: SubscribeAnnouncement
        in: body
        name: subscribe_announcement
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Device'
      tags:
      - device
swagger: "2.0"
